### ISSUE TITLE
Feature request: Orchard Street word list for Dvorak and Colemak typists

### ISSUE THREAD

**Issue by atoponce** [sts10/orchard-street-wordlists#3]
I'm a Dvorak typist myself, so I would be especially interested in what such a word list would look like. Also knowing that Colemak has found a strong following of typists, it would be interesting to see that list as well.

Of course, both of us are niche typists compared to the larger typing world, so it's understandable if you make this request very low priority.

**Comment by sts10** [comment]
Oh, interesting. I'm guessing you're referring to the short lists, which are optimized for low travel distance on two different keyboard layouts. 

These lists are actually just copied over from [this project](https://github.com/sts10/remote-words). As explained in that project's documentation, these word lists are intended for use when users must enter their password via a TV remote or video game controller. When using all your fingers on a real keyboard, I don't think low travel distance is that important. 

I don't think many users would ever find themselves confronted with a TV/video game keyboard laid out in Dvorak or Colemak, but I could be wrong? We can discuss over [there](https://github.com/sts10/remote-words).

**Comment by atoponce** [comment]
Ah, I see. That makes more sense. Thanks.
